# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Problems with Puffins
email: bojan.bozic@tudublin.ie
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about cool problems and their solutions, crazy ideas, tech news, 
  algorithms with puffins, and many other topics in Semantic Web, Machine Learning, Natural Language Processing,
  and any other awesome research field that might come to my attention :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bojan_bozic
github_username:  bozicb
linkedin_link: https://www.linkedin.com/in/bojan-bozic/
title_image: "images/title.jpg"

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
gems:
 - jekyll-jupyter-notebook
