---
title: "PSILectureDimRed"
author: "HTML"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#  This is an accompaniment to the lecture Dimension Reduction.
##  It includes all the examples used in the lecture

### Preliminaries

```{r}


library(corpcor)
library(GPArotation)
library(psych)
library(REdaS)
library(Hmisc)
library(corrplot)
library(ggcorrplot)
library(factoextra)
library(nFactors)

```


```{r}
#We are using a .dat file from Field, Miles and Field Discovering Statistics with R, a survey on fear of statistics - raq.dat
#load data
raqData<-read.delim("../data/raq.dat", header = TRUE)

#create a correlation matrix (these are just some methods)
raqMatrix<-cor(raqData)
round(raqMatrix, 2)
Hmisc::rcorr(as.matrix(raqData))

```

###Using ggcorrplot
```{r }
#Using ggcorrplot
p.mat <- ggcorrplot::cor_pmat(raqData)
ggcorrplot::ggcorrplot(raqMatrix, title = "Correlation matrix for RAQ data")
#Showing Xs for non-significant correlations
ggcorrplot::ggcorrplot(raqMatrix, title = "Correlation matrix for RAQ data", p.mat = p.mat, sig.level = .05)
#Showing lower diagonal
ggcorrplot::ggcorrplot(raqMatrix, title = "Correlation matrix for RAQ data", p.mat = p.mat, sig.level = .05, type="lower")
#Showing the co-efficients 
ggcorrplot::ggcorrplot(raqMatrix, lab=TRUE, title = "Correlation matrix for RAQ data",  type="lower")

```
###Using corrplot
```{r}
#Visualisation of correlations using circles
#corrplot parameters method = c("circle", "square", "ellipse", "number", "shade",
#"color", "pie")
#type = c("full", "lower", "upper"),
corrplot::corrplot(raqMatrix, method="circle")
corrplot::corrplot(raqMatrix, method="circle", type="upper")
#Visualisation using numbers
corrplot::corrplot(raqMatrix, method="number")

#Visualisation of significance levels at 0.05
res1 <- corrplot::cor.mtest(raqMatrix, conf.level = .95)
corrplot::corrplot(raqMatrix, p.mat = res1$p, type="lower", sig.level = .05)

#Showing p-value for non-significant results
corrplot(raqMatrix, p.mat = res1$p, type="lower",insig = "p-value")
```

```{r}

```


###Initial Statistics
```{r}
#Bartlett's test
psych::cortest.bartlett(raqData)
psych::cortest.bartlett(raqMatrix, n = 2571)

#KMO (execute one of these):
REdaS::KMOS(raqData)
psych::KMO(raqData)

#Determinent (execute one of these):
det(raqMatrix)
det(cor(raqData))
```
##Principal Components Analysis (PCA)

```{r}
#pcModel<-principal(dataframe/R-matrix, nfactors = number of factors, rotate = "method of rotation", scores = TRUE)

#On raw data using principal components analysis
#For PCA we know how many factors if is possible to find
#principal will work out our loadings of each variable onto each component, the proportion each component explained and the cummulative proportion of variance explai 
pc1 <-  principal(raqData, nfactors = 23, rotate = "none")
pc1 <-  principal(raqData, nfactors = length(raqData), rotate = "none")
pc1#output all details of the PCA
psych::print.psych(pc1, cut = 0.3, sort = TRUE)


fa.diagram(pc1) #create a diagram showing the components and how the manifest variables load
fa.sort(pc1$loading) #Loadings of variables on to components
pc1$communality #Communalities of variables across components (will be one for PCA since all the variance is used)

plot(pc1$values, type = "b") #scree plot
pc1$Vaccounted
pc1$values #output eigenvalues
#Another way to look at eigen values plus variance explained (need to use princomp function fof PCA to get right class for use with factoextra dunctions)
pcf=princomp(raqData)
factoextra::get_eigenvalue(pcf)
factoextra::fviz_eig(pcf, addlabels = TRUE, ylim = c(0, 50))#Visualise the Eigenvalues
factoextra::fviz_pca_var(pcf, col.var = "black")
factoextra::fviz_pca_var(pcf, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )
#VIsualise contribution of variables
var <- factoextra::get_pca_var(pcf)
corrplot::corrplot(var$contrib, is.corr=FALSE) 

# Contributions of variables to PC1
factoextra::fviz_contrib(pcf, choice = "var", axes = 1, top = 10)
# Contributions of variables to PC2
factoextra::fviz_contrib(pcf, choice = "var", axes = 2, top = 10)

#PCA with rotation
pc2 <-  principal(raqData, nfactors = 4, rotate = "varimax")#Extracting 4 factors
psych::print.psych(pc2, cut = 0.3, sort = TRUE)
pc2$communality



```
##Factor Analysis
```{r}
#Factor Analysis

#Principal Axis Factoring
pc3 <- fa(raqMatrix, nfactors=4, obs=NA, n.iter=1, rotate="varimax", fm="pa")
psych::print.psych(pc3,cut=0.3, sort=TRUE)

fa.sort(pc3$loading)
fa.diagram(pc3)#create a diagram showing the factors and how the manifest variables load
plot(pc3$values, type = "b") #scree plot

pc3$Vaccounted#Variance accounted for
pc3$values #output eigenvalues

```
##Reliability Analysis
```{r}

computerFear<-raqData[,c(6, 7, 10, 13, 14, 15, 18)]
statisticsFear <- raqData[, c(1, 3, 4, 5, 12, 16, 20, 21)]
mathFear <- raqData[, c(8, 11, 17)]
peerEvaluation <- raqData[, c(2, 9, 19, 22, 23)]


psych::alpha(computerFear)
psych::alpha(statisticsFear, keys = c(1, -1, 1, 1, 1, 1, 1, 1))
psych::alpha(mathFear)
psych::alpha(peerEvaluation)
psych::alpha(statisticsFear) #for illustrative pruposes
```

