---
title: "PSIWeek4Practical"
author: "HTML"
date: "27 September 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Exercises 1 to 5
```{r}

#Inspecting the data
#Remember to install these packages if you haven't already done so
library(foreign)
library(pastecs) #For creating descriptive statistic summaries
library(ggplot2) #For creating histograms with more detail than plot
library(psych) # Some useful descriptive functions
library(semTools) #For skewness and kurtosis
library(car) # For Levene's test for homogeneity of variance



#Read in the file
regression <- read.spss("Regression.sav", use.value.labels=TRUE, max.value.labels=Inf, to.data.frame=TRUE)

#Setting the column names to be that used in the dataset
colnames(regression) <- tolower(colnames(regression))

```



### Differences - Parametric Tests
#### Independent t-test
```{r}
#Get descriptive stastitics by group
#describeBy is part of the psych package so you need to use it
describeBy(regression$normexam,group=regression$girl)

#Conduct Levene's test for homogeneity of variance in library car
#The original regression.sav did not have labels for girl so to get the leveneTest to work
#We need to include a factoring of giorl to make sure the tests works
#leveneTest(normexam~factor(girl), data=regression)
#I've uploaded a corrected version with labels
leveneTest(normexam~girl, data=regression)
#Test is significant so we can't assume homogeneity of variance

#Conduct the t-test
#You can use the var.equal = TRUE option to specify equal variances and a pooled variance estimate
t.test(normexam~girl,data=regression)
#We get a statistically significant result
```
#Exercise 6 to (only for selected variables)
```{r}
#We are using a .dat file (survey.dat) created from the SPSS file survey.sav  taken from SPSS Survival Manual 6th Edition Julie Pallant
#http://spss.allenandunwin.com.s3-website-ap-southeast-2.amazonaws.com/data-files.html#.Wb0vvnWP-po
#Results on a survey on well being
#We need to load the file so that we can use it in R.
survey <- read.table("C:/tempR/survey.dat")
#Setting the column names to be that used in the dataset
colnames(survey) <- tolower(colnames(survey))

#Descriptive Statistics for Postive Affect, Negative Affect, Self-Esteem, Life Satisfaction
format(stat.desc(survey$tposaff), scientific=FALSE)
#skewness and kurtosis from semTools with standard error 
skew<-skew(survey$tposaff) 
#There is an issue with skewness
kurt<-kurtosis(survey$tposaff)
skew[1]/skew[2]
kurt[1]/kurt[2]

#Create standardised scores, enought are falling within 95 CI to treat as normal
sort(scale(survey$tposaff))
format(stat.desc(survey$tnegaff), scientific=FALSE)
skew<-semTools::skew(survey$tnegaff) 
#There is an issue with skewness
kurt<-semTools::kurtosis(survey$tnegaff)
skew[1]/skew[2]
kurt[1]/kurt[2]
#Create standardised scores, enought are falling within 95 CI to treat as normal
sort(scale(survey$tnegaff))
format(stat.desc(survey$tslfest), scientific=FALSE)
skew<-skew(survey$tslfest) 
#There is an issue with skewness
kurt<-kurtosis(survey$tslfest)
skew[1]/skew[2]
kurt[1]/kurt[2]
#Create standardised scores, enought are falling within 95 CI to treat as normal
sort(scale(survey$tslfest))
format(stat.desc(survey$tlifesat), scientific=FALSE)
skew<-semTools::skew(survey$tlifesat) 
kurt<-semTools::kurtosis(survey$tlifesat)
#Both Skew and Kurtosis are fine
skew[1]/skew[2]
kurt[1]/kurt[2]


#Histograms of postive affect  process is similar for all
gg <- ggplot(survey, aes(x=survey$tposaff))
#Change the label of the x axis
gg <- gg + labs(x="Positive Affect")
#manage binwidth and colours
gg <- gg + geom_histogram(binwidth=2, colour="black", aes(y=..density.., fill=..count..))
gg <- gg + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")


#adding a normal curve
#use stat_function to compute a normalised score for each value of normexam
#pass the mean and standard deviation
#use the na.rm parameter to say how missing values are handled
gg <- gg + stat_function(fun=dnorm, color="red",args=list(mean=mean(survey$tposaff, na.rm=TRUE), sd=sd(survey$tposaff, na.rm=TRUE)))
#to display the graph request the contents of the variable be shown
gg
#Create a qqplot
qqnorm(survey$tposaff)
qqline(survey$tposaff, col=2) #show a line on theplot


```

###Correlations
```{r}
#Perceived stress and self-esteem; Perceived stress and positive affect; Positive affect and Life Satisfaction
#Simple scatter
scatter <- ggplot(survey, aes(survey$tposaff, survey$tslfest))
#Add a regression line
scatter <- scatter + geom_point() + geom_smooth(method = "lm", colour = "Red", se = F) + labs(x = "Positive Affect", y = "Total Self-Esteem") 
scatter

cor.test(survey$tposaff, survey$tslfest, method='pearson')

#Simple scatter
scatter <- ggplot(survey, aes(survey$tposaff, survey$tpstress))
#Add a regression line
scatter <- scatter + geom_point() + geom_smooth(method = "lm", colour = "Red", se = F) + labs(x = "Positive Affect", y = "Total Perceived Stress")
scatter

cor.test(survey$tposaff, survey$tpstress, method='pearson')

#Simple scatter
scatter <- ggplot(survey, aes(survey$tposaff, survey$tlifesat))
#Add a regression line
scatter <- scatter + geom_point() + geom_smooth(method = "lm", colour = "Red", se = F) + labs(x = "Positive Affect", y = "Life Satisfaction")
scatter
cor.test(survey$tposaff, survey$tlifesat, method='pearson')

```
Our correlation level is strong positive and statistically significant


### Differences - Parametric Tests
#### Independent t-test
```{r}
#Get descriptive stastitics by group
#describeBy is part of the psych package so you need to use it
describeBy(survey$tposaff,group=survey$sex)

#Conduct Levene's test for homogeneity of variance in library car
leveneTest(tposaff~sex, data=survey)
#Test is not significant so we can assume homogeneity of variance
#Conduct the t-test
t.test(tposaff~sex, var.equal = TRUE,data=survey)
#Test statistic is not statistically significant


#describeBy is part of the psych package so you need to use it
describeBy(survey$tnegaff,group=survey$sex)
#Conduct Levene's test for homogeneity of variance in library car
leveneTest(tnegaff~sex, data=survey)
#Test is not significant so we can assume homogeneity of variance
#Conduct the t-test
t.test(tnegaff~sex, var.equal = TRUE,data=survey)
#Test statistic is not statistically significant

#describeBy is part of the psych package so you need to use it
describeBy(survey$tlifesat,group=survey$sex)
#Conduct Levene's test for homogeneity of variance in library car
leveneTest(tlifesat~sex, data=survey)
#Test is not significant so we can assume homogeneity of variance
#Conduct the t-test
t.test(tlifesat~sex, var.equal = TRUE,data=survey)
#Test Statistic is not statistically sinigicant


```