---
title: "Week 5 - Probability and Statistics"
subtitle: " Difference"
author: "HTML"
output: html_document
editor_options: 
chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

#  This is an accompaniment to the lecture on  difference
##  It includes all the examples used in the lecture


 
### SETUP
```{r}
#We are using a .dat file (survey.dat) created from the SPSS file survey.sav  taken from SPSS Survival Manual 6th Edition Julie Pallant
#http://spss.allenandunwin.com.s3-website-ap-southeast-2.amazonaws.com/data-files.html#.Wb0vvnWP-po
#Results on a survey on well being
#We need to load the file so that we can use it in R.
survey <- read.table("../data/survey.dat")
#Setting the column names to be that used in the dataset
colnames(survey) <- tolower(colnames(survey))

#Inspecting the data
#Remember to install these packages if you haven't already done so

library(pastecs) #For creating descriptive statistic summaries
library(ggplot2) #For creating histograms with more detail than plot
library(psych) # Some useful descriptive functions
library(semTools) #For skewness and kurtosis
library(car) # For Levene's test for homogeneity of variance 
library(coin)# For Wilcox test (non-parametric)
```


### Differences - Parametric Tests
#### Independent t-test
```{r}
#Get descriptive stastitics by group
describeBy(survey$tslfest, survey$sex)


#Conduct Levene's test for homogeneity of variance in library car
ltest<-car::leveneTest(tslfest ~ sex, data=survey)
#Pr(F) is your probability
ltest

#Conduct the t-test from package stats
#You can use the var.equal = TRUE option to specify equal variances and a pooled variance estimate
stats::t.test(tslfest~sex,var.equal=TRUE,data=survey)

```
### Differences - Non-Parametric Tests
#### Mann Whitney U Test
```{r}
drinkset<- read.table("../data/Field-BDI-Non-parametric.dat")
#Get your descriptive statistcs
describeBy(drinkset$bdisun,group=drinkset$drink)
#Create data subsets for each drink
vodkadata <- subset(drinkset, drink=='Vodka')
beerdata <-subset(drinkset, drink=='Beer')

#Create plots of these
gs <- ggplot(vodkadata, aes(x=vodkadata$bdisun))
gs <- gs + labs(x="Vodka")
gs <- gs + geom_histogram(binwidth=2, colour="black", aes(y=..density.., fill=..count..))
gs <- gs + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")
gs <- gs + stat_function(fun=dnorm, color="red",args=list(mean=mean(vodkadata$bdisun, na.rm=TRUE), sd=sd(vodkadata$bdisun, na.rm=TRUE)))
gs

gs <- ggplot(beerdata, aes(x=beerdata$bdisun))
gs <- gs + labs(x="Beer")
gs <- gs + geom_histogram(binwidth=2, colour="black", aes(y=..density.., fill=..count..))
gs <- gs + scale_fill_gradient("Count", low="#DCDCDC", high="#7C7C7C")
gs <- gs + stat_function(fun=dnorm, color="red",args=list(mean=mean(beerdata$bdisun, na.rm=TRUE), sd=sd(beerdata$bdisun, na.rm=TRUE)))
gs

# Test for differences on  Sunday
stats::wilcox.test(bdisun~drink, data=drinkset) 
# Test for differences on Wednesday
stats::wilcox.test(bdiwed~drink, data=drinkset) 

# Test for differences on  Sunday
coin::wilcox_test(bdisun~drink, data=drinkset) 
# Test for differences on Wednesday
coin::wilcox_test(bdiwed~drink, data=drinkset) 
```

```{r}
#Paired T-test:
#t.test(y1,y2,paired=TRUE) # where y1 & y2 are numeric
#Experiment - fear of statistics
edata<-read.table('../data/experim.dat')
# Difference between FearFor our example:
t.test(edata$fost1,edata$fost2,paired=TRUE)

```
```{r}
#Non-parametric Repeated measure
#We are using the drink dataset again
#Need to split the file or subset it  and run against each sub-set
vodkadata<-subset(drinkset,drinkset$drink=='Vodka')
beerdata<-subset(drinkset,drinkset$drink=='Beer')


summary(vodkadata)
summary(beerdata)
#Wilcoxon test syntax
#stats::wilcox.test(y1,y2,paired=TRUE)

stats::wilcox.test(vodkadata$bdisun,vodkadata$bdiwed,paired=TRUE)
stats::wilcox.test(beerdata$bdisun,beerdata$bdiwed,paired=TRUE)


```



